// Auto-generated lightweight metadata for OG image generation
// Avoids importing full posts.ts (27K+ lines) into edge functions

export interface BlogMeta { title: string; category: string; readTime: string }

export const blogMeta: Record<string, BlogMeta> = {
  'how-to-create-tax-invoice-australia': { title: `How to Create a Tax Invoice in Australia (2026 Guide)`, category: 'Invoicing', readTime: '8 min read' },
  'gst-guide-australian-freelancers': { title: `GST for Australian Freelancers: Complete 2026 Guide`, category: 'Tax', readTime: '10 min read' },
  'invoicing-international-clients-australia': { title: `How to Invoice International Clients from Australia (2026)`, category: 'Invoicing', readTime: '9 min read' },
  'best-invoicing-software-australia': { title: `Best Invoicing Software for Australian Freelancers (2026)`, category: 'Business', readTime: '12 min read' },
  'sole-trader-vs-company-australia': { title: `Sole Trader vs Company in Australia: Which Structure for Freelancers?`, category: 'Business', readTime: '10 min read' },
  'why-freelancers-dont-need-accounting-software': { title: `Why Freelancers Don\'t Need Accounting Software (Just Invoicing)`, category: 'Business', readTime: '8 min read' },
  'get-clients-pay-invoices-faster': { title: `How to Get Clients to Pay Invoices Faster (7 Proven Tactics)`, category: 'Invoicing', readTime: '9 min read' },
  'freelance-invoice-checklist': { title: `What Should a Freelance Invoice Include? (Complete Checklist)`, category: 'Invoicing', readTime: '7 min read' },
  'freelance-rates-australia': { title: `Freelance Rates in Australia: What to Charge in 2026`, category: 'Business', readTime: '7 min read' },
  'tax-deductions-australian-freelancers': { title: `Tax Deductions for Australian Freelancers: The Complete 2026 Guide`, category: 'Tax', readTime: '10 min read' },
  'bas-guide-australian-freelancers': { title: `BAS for Freelancers: How to Lodge Your Business Activity Statement`, category: 'Tax', readTime: '9 min read' },
  'how-to-register-abn-australia': { title: `How to Get an ABN in Australia: Freelancer Registration Guide`, category: 'Getting Started', readTime: '8 min read' },
  'superannuation-for-freelancers-australia': { title: `Superannuation for Australian Freelancers: Complete Guide (2026)`, category: 'Tax', readTime: '10 min read' },
  'late-payment-fees-australia-freelancers': { title: `Late Payment Fees in Australia: What Freelancers Can Legally Charge`, category: 'Getting Paid', readTime: '8 min read' },
  'how-to-start-freelancing-australia': { title: `How to Start Freelancing in Australia: Complete Beginner Guide (2026)`, category: 'Getting Started', readTime: '12 min read' },
  'freelance-contract-australia': { title: `How to Write a Freelance Contract in Australia (2026)`, category: 'Business', readTime: '10 min read' },
  'record-keeping-freelancers-australia': { title: `Record Keeping for Freelancers in Australia: ATO Requirements`, category: 'Tax', readTime: '9 min read' },
  'how-to-quote-clients-freelancer': { title: `How to Quote Clients as a Freelancer in Australia`, category: 'Business', readTime: '9 min read' },
  'how-much-tax-freelancers-pay-australia': { title: `How Much Tax Do Freelancers Pay in Australia? (2025-26 Guide)`, category: 'Tax', readTime: '10 min read' },
  'freelancer-insurance-guide-australia': { title: `Freelancer Insurance Guide Australia: What Cover Do You Actually Need?`, category: 'Business', readTime: '10 min read' },
  'how-to-accept-payments-freelancer-australia': { title: `How to Accept Payments as a Freelancer in Australia (2026 Guide)`, category: 'Invoicing', readTime: '9 min read' },
  'sole-trader-tax-return-australia': { title: `Sole Trader Tax Return Australia: Complete 2026 Guide`, category: 'Tax', readTime: '11 min read' },
  'contractor-vs-employee-australia': { title: `Contractor vs Employee in Australia: Know the Difference`, category: 'Business', readTime: '10 min read' },
  'cashflow-management-freelancers-australia': { title: `Cash Flow Management for Australian Freelancers: The Complete Guide`, category: 'Business', readTime: '10 min read' },
  'working-from-home-tax-deductions-australia': { title: `Working from Home Tax Deductions Australia: Complete 2026 Guide`, category: 'Tax', readTime: '11 min read' },
  'freelancing-vs-full-time-employment-australia': { title: `Freelancing vs Full-Time Employment in Australia: Honest Comparison`, category: 'Getting Started', readTime: '12 min read' },
  'how-to-price-freelance-services-australia': { title: `How to Price Your Freelance Services in Australia (Beyond Hourly Rates)`, category: 'Business', readTime: '11 min read' },
  'best-business-bank-accounts-freelancers-australia': { title: `Best Business Bank Accounts for Freelancers in Australia (2026)`, category: 'Business', readTime: '11 min read' },
  'how-to-find-freelance-clients-australia': { title: `How to Find Freelance Clients in Australia: 12 Proven Strategies`, category: 'Growth', readTime: '13 min read' },
  'freelance-portfolio-guide-australia': { title: `Freelance Portfolio Guide: How to Win More Clients (2026)`, category: 'Growth', readTime: '10 min read' },
  'common-invoicing-mistakes-freelancers': { title: `11 Invoicing Mistakes That Cost Australian Freelancers Money`, category: 'Invoicing', readTime: '9 min read' },
  'how-to-chase-overdue-invoices-australia': { title: `How to Chase Overdue Invoices Without Damaging Client Relationships`, category: 'Getting Paid', readTime: '10 min read' },
  'payment-reminder-email-templates-freelancers': { title: `Payment Reminder Email Templates for Australian Freelancers (2026)`, category: 'Getting Paid', readTime: '10 min read' },
  'payg-instalments-australian-freelancers': { title: `PAYG Instalments for Australian Freelancers: Complete Guide (2026)`, category: 'Tax', readTime: '10 min read' },
  'how-to-handle-scope-creep-freelancer': { title: `How to Handle Scope Creep as a Freelancer (Without Losing Clients)`, category: 'Business', readTime: '9 min read' },
  'freelancer-tax-calendar-australia-2026': { title: `Australian Freelancer Tax Calendar 2026: Every Deadline You Need`, category: 'Tax', readTime: '8 min read' },
  'how-to-raise-freelance-rates-australia': { title: `How to Raise Your Freelance Rates in Australia (Without Losing Clients)`, category: 'Pricing', readTime: '10 min read' },
  'retainer-agreements-australian-freelancers': { title: `Retainer Agreements for Australian Freelancers: The Complete Guide`, category: 'Pricing', readTime: '11 min read' },
  'time-tracking-australian-freelancers': { title: `Time Tracking for Australian Freelancers: Why It Matters (Even for Fixed-Price Work)`, category: 'Business', readTime: '9 min read' },
  'how-to-write-freelance-proposal-australia': { title: `How to Write a Freelance Proposal That Wins (With Templates)`, category: 'Growth', readTime: '11 min read' },
  'freelance-client-red-flags-australia': { title: `Freelance Client Red Flags: 12 Warning Signs Before You Start`, category: 'Growth', readTime: '10 min read' },
  'how-to-fire-client-professionally-freelancer': { title: `How to Fire a Client Professionally as a Freelancer`, category: 'Business', readTime: '9 min read' },
  'freelance-bookkeeping-australia': { title: `Freelance Bookkeeping: Simple System for Australian Freelancers (2026)`, category: 'Business', readTime: '10 min read' },
  'invoice-payment-terms-explained': { title: `Invoice Payment Terms Explained: Net 7, 14, 30 Guide for Freelancers`, category: 'Invoicing', readTime: '9 min read' },
  'how-to-handle-client-disputes-freelancer-australia': { title: `How to Handle Client Disputes as a Freelancer in Australia`, category: 'Getting Paid', readTime: '11 min read' },
  'freelance-tools-stack-australia': { title: `Essential Freelance Tools Stack for Australian Freelancers (2026)`, category: 'Getting Started', readTime: '10 min read' },
  'how-to-get-repeat-clients-freelancer': { title: `How to Get Repeat Clients and Build Recurring Revenue as a Freelancer`, category: 'Growth', readTime: '9 min read' },
  'digital-marketing-freelancers-australia': { title: `Digital Marketing for Freelancers: How to Get Found Online Without a Big Budget`, category: 'Growth', readTime: '11 min read' },
  'ai-tools-for-freelancers-australia': { title: `Best AI Tools for Australian Freelancers in 2026`, category: 'Business', readTime: '11 min read' },
  'transition-full-time-to-freelancing-australia': { title: `How to Transition from Full-Time to Freelancing in Australia`, category: 'Getting Started', readTime: '13 min read' },
  'freelance-tax-mistakes-australia': { title: `15 Freelance Tax Mistakes That Cost Australians Thousands`, category: 'Tax', readTime: '10 min read' },
  'deposit-invoicing-milestone-payments-freelancer': { title: `How to Invoice for Deposits and Milestone Payments as a Freelancer`, category: 'Invoicing', readTime: '9 min read' },
  'freelance-networking-australia': { title: `Freelance Networking: How to Build Professional Connections in Australia`, category: 'Growth', readTime: '10 min read' },
  'financial-planning-australian-freelancers': { title: `Financial Planning for Australian Freelancers: Budget, Save, and Grow Your Wealth`, category: 'Business', readTime: '12 min read' },
  'invoice-numbering-system-freelancers': { title: `Invoice Numbering System for Freelancers: Complete Guide`, category: 'Invoicing', readTime: '8 min read' },
  'invoice-email-templates-freelancers': { title: `How to Write Invoice Emails That Get Paid Faster (With Templates)`, category: 'Getting Paid', readTime: '9 min read' },
  'intellectual-property-rights-freelancers-australia': { title: `Intellectual Property Rights for Australian Freelancers: Who Owns Your Work?`, category: 'Business', readTime: '10 min read' },
  'managing-multiple-freelance-clients-australia': { title: `How to Manage Multiple Freelance Clients Without Burning Out`, category: 'Business', readTime: '11 min read' },
  'recurring-invoices-guide-freelancers': { title: `Recurring Invoices: Set-and-Forget Billing for Freelance Retainers`, category: 'Invoicing', readTime: '9 min read' },
  'setting-boundaries-freelance-clients': { title: `How to Set Boundaries with Freelance Clients (Without Losing Them)`, category: 'Business', readTime: '10 min read' },
  'freelance-business-plan-australia': { title: `How to Write a Freelance Business Plan (Australia 2026 Guide)`, category: 'Business', readTime: '11 min read' },
  'client-onboarding-checklist-freelancers': { title: `Client Onboarding Checklist for Freelancers: Start Every Project Right`, category: 'Business', readTime: '10 min read' },
  'freelance-work-life-balance-burnout-australia': { title: `Freelance Work-Life Balance: How to Avoid Burnout While Growing Your Business`, category: 'Business', readTime: '10 min read' },
  'how-to-send-first-invoice-freelancer': { title: `How to Send Your First Invoice as a Freelancer (Complete Guide)`, category: 'Getting Started', readTime: '9 min read' },
  'subcontracting-guide-australian-freelancers': { title: `Subcontracting for Australian Freelancers: Tax, TPAR & Payments`, category: 'Business', readTime: '10 min read' },
  'credit-notes-refunds-australian-freelancers': { title: `Credit Notes and Refunds: A Guide for Australian Freelancers`, category: 'Invoicing', readTime: '8 min read' },
  'eofy-tax-prep-checklist-freelancers-australia': { title: `EOFY Tax Prep Checklist for Australian Freelancers (2025-26)`, category: 'Tax', readTime: '11 min read' },
  'freelance-project-management-deliver-on-time': { title: `Freelance Project Management: How to Deliver Work on Time and on Budget`, category: 'Business', readTime: '10 min read' },
  'vehicle-travel-expenses-freelancers-australia': { title: `Vehicle and Travel Expenses for Australian Freelancers (2025-26 Guide)`, category: 'Tax', readTime: '10 min read' },
  'personal-branding-freelancers-australia': { title: `How to Build a Personal Brand as a Freelancer in Australia`, category: 'Growth', readTime: '11 min read' },
  'how-to-scale-freelance-business-australia': { title: `How to Scale a Freelance Business in Australia (Beyond Trading Time for Money)`, category: 'Business', readTime: '12 min read' },
  'freelance-negotiation-skills-australia': { title: `Freelance Negotiation Skills: How to Get Better Rates and Terms in Australia`, category: 'Pricing', readTime: '10 min read' },
  'digital-products-freelancer-australia': { title: `How to Create and Sell Digital Products as a Freelancer in Australia`, category: 'Business', readTime: '11 min read' },
  'freelance-cybersecurity-australia': { title: `Freelance Cybersecurity: Protecting Your Business and Client Data in Australia`, category: 'Business', readTime: '10 min read' },
  'email-marketing-freelancers-australia': { title: `Email Marketing for Freelancers: How to Build a Client Pipeline on Autopilot`, category: 'Growth', readTime: '10 min read' },
  'invoice-vs-receipt-vs-quote-difference': { title: `Invoice vs Receipt vs Quote: What\'s the Difference? (Australian Guide)`, category: 'Invoicing', readTime: '10 min read' },
  'proforma-invoice-guide-australian-freelancers': { title: `Proforma Invoices for Australian Freelancers: When and How to Use Them`, category: 'Invoicing', readTime: '9 min read' },
  'how-to-niche-down-freelancer-australia': { title: `How to Niche Down as a Freelancer in Australia (And Charge More)`, category: 'Growth', readTime: '11 min read' },
  'government-grants-funding-australian-freelancers': { title: `Government Grants and Funding for Australian Freelancers and Sole Traders`, category: 'Business', readTime: '11 min read' },
  'non-paying-clients-legal-options-australia': { title: `Non-Paying Clients in Australia: Your Legal Options as a Freelancer`, category: 'Getting Paid', readTime: '11 min read' },
  'freelancing-on-visa-australia-work-rights-tax': { title: `Freelancing on a Visa in Australia: Work Rights, Tax, and ABN Rules`, category: 'Getting Started', readTime: '12 min read' },
  'ato-audit-guide-australian-freelancers': { title: `How to Handle an ATO Audit as an Australian Freelancer`, category: 'Tax', readTime: '10 min read' },
  'professional-development-tax-deductions-freelancers-australia': { title: `Professional Development Tax Deductions for Australian Freelancers`, category: 'Tax', readTime: '8 min read' },
  'diversify-freelance-income-streams-australia': { title: `How to Diversify Your Freelance Income (Beyond Client Work)`, category: 'Business', readTime: '10 min read' },
  'freelancing-while-employed-australia': { title: `Freelancing While Employed in Australia: Side Hustle Rules, Tax & Legal Guide (2026)`, category: 'Getting Started', readTime: '11 min read' },
  'gst-registration-threshold-australian-freelancers': { title: `GST Registration Threshold: When Must Australian Freelancers Register? (2026 Guide)`, category: 'Tax', readTime: '10 min read' },
  'invoicing-expenses-reimbursements-freelancer-australia': { title: `How to Invoice for Expenses and Reimbursements as an Australian Freelancer (2026)`, category: 'Invoicing', readTime: '9 min read' },
  'invoicing-graphic-designers-australia': { title: `How to Invoice as a Freelance Graphic Designer in Australia (2026)`, category: 'Invoicing', readTime: '10 min read' },
  'invoicing-web-developers-australia': { title: `How to Invoice as a Freelance Web Developer in Australia (2026)`, category: 'Invoicing', readTime: '11 min read' },
  'invoicing-photographers-australia': { title: `How to Invoice as a Freelance Photographer in Australia (2026)`, category: 'Invoicing', readTime: '10 min read' },
  'invoicing-copywriters-content-writers-australia': { title: `How to Invoice as a Freelance Copywriter in Australia (2026 Guide)`, category: 'Invoicing', readTime: '11 min read' },
  'invoicing-social-media-managers-australia': { title: `How to Invoice as a Freelance Social Media Manager in Australia (2026 Guide)`, category: 'Invoicing', readTime: '10 min read' },
  'invoicing-videographers-video-editors-australia': { title: `How to Invoice as a Freelance Videographer in Australia (2026 Guide)`, category: 'Invoicing', readTime: '11 min read' },
  'invoicing-consultants-australia': { title: `How to Invoice as a Freelance Consultant in Australia (2026)`, category: 'Invoicing', readTime: '11 min read' },
  'invoicing-bookkeepers-bas-agents-australia': { title: `How to Invoice as a Freelance Bookkeeper in Australia (2026)`, category: 'Invoicing', readTime: '10 min read' },
  'invoicing-personal-trainers-fitness-australia': { title: `How to Invoice as a Freelance Personal Trainer in Australia (2026)`, category: 'Invoicing', readTime: '10 min read' },
  'invoicing-virtual-assistants-australia': { title: `How to Invoice as a Freelance Virtual Assistant in Australia (2026)`, category: 'Invoicing', readTime: '10 min read' },
  'invoicing-interior-designers-australia': { title: `How to Invoice as a Freelance Interior Designer in Australia (2026)`, category: 'Invoicing', readTime: '11 min read' },
  'invoicing-electricians-tradespeople-australia': { title: `How to Invoice as a Freelance Electrician or Tradesperson in Australia (2026)`, category: 'Invoicing', readTime: '11 min read' },
  'invoicing-massage-therapists-allied-health-australia': { title: `How to Invoice as a Freelance Massage Therapist or Allied Health Practitioner in Australia`, category: 'Invoicing', readTime: '18 min read' },
  'invoicing-tutors-private-teachers-australia': { title: `How to Invoice as a Freelance Tutor or Private Teacher in Australia`, category: 'Invoicing', readTime: '16 min read' },
  'invoicing-makeup-artists-hair-stylists-australia': { title: `How to Invoice as a Freelance Makeup Artist or Hair Stylist in Australia`, category: 'Invoicing', readTime: '17 min read' },
  'invoicing-cleaners-cleaning-business-australia': { title: `How to Invoice as a Cleaner or Cleaning Business in Australia (2026 Guide)`, category: 'Profession Guides', readTime: '12 min read' },
  'invoicing-yoga-pilates-instructors-australia': { title: `How to Invoice as a Yoga or Pilates Instructor in Australia (2026 Guide)`, category: 'Profession Guides', readTime: '12 min read' },
  'invoicing-carpenters-builders-australia': { title: `How to Invoice as a Carpenter or Builder in Australia (2026 Guide)`, category: 'Profession Guides', readTime: '13 min read' },
  'invoicing-musicians-djs-australia': { title: `How to Invoice as a Freelance Musician or DJ in Australia (2026 Guide)`, category: 'Profession Guides', readTime: '14 min read' },
  'invoicing-architects-draftspeople-australia': { title: `How to Invoice as a Freelance Architect or Draftsperson in Australia (2026 Guide)`, category: 'Profession Guides', readTime: '14 min read' },
  'invoicing-event-planners-wedding-coordinators-australia': { title: `How to Invoice as a Freelance Event Planner or Wedding Coordinator in Australia (2026 Guide)`, category: 'Profession Guides', readTime: '13 min read' },
  'invoicing-it-consultants-cybersecurity-australia': { title: `How to Invoice as a Freelance IT Consultant or Cybersecurity Specialist in Australia`, category: 'Invoicing', readTime: '14 min read' },
  'invoicing-caterers-private-chefs-australia': { title: `How to Invoice as a Freelance Caterer or Private Chef in Australia`, category: 'Profession Guides', readTime: '13 min read' },
  'invoicing-landscapers-gardeners-australia': { title: `How to Invoice as a Freelance Landscaper or Gardener in Australia`, category: 'Invoicing', readTime: '13 min read' },
  'invoicing-plumbers-gas-fitters-australia': { title: `How to Invoice as a Freelance Plumber or Gas Fitter in Australia`, category: 'Invoicing', readTime: '14 min read' },
  'invoicing-life-coaches-business-coaches-australia': { title: `How to Invoice as a Life Coach or Business Coach in Australia`, category: 'Invoicing', readTime: '13 min read' },
  'invoicing-dog-walkers-pet-sitters-australia': { title: `How to Invoice as a Dog Walker or Pet Sitter in Australia`, category: 'Invoicing', readTime: '12 min read' },
  'invoicing-accountants-tax-agents-bas-agents-australia': { title: `How to Invoice as a Freelance Accountant, Tax Agent, or BAS Agent in Australia`, category: 'Invoicing', readTime: '14 min read' },
  'invoicing-translators-interpreters-australia': { title: `How to Invoice as a Freelance Translator or Interpreter in Australia`, category: 'Invoicing', readTime: '13 min read' },
  'invoicing-ux-ui-designers-australia': { title: `How to Invoice as a Freelance UX/UI Designer in Australia`, category: 'Invoicing', readTime: '13 min read' },
  'invoicing-psychologists-counsellors-therapists-australia': { title: `How to Invoice as a Psychologist, Counsellor, or Therapist in Australia`, category: 'Invoicing', readTime: '15 min read' },
  'invoicing-florists-floral-designers-australia': { title: `How to Invoice as a Freelance Florist or Floral Designer in Australia`, category: 'Invoicing', readTime: '13 min read' },
  'invoicing-driving-instructors-australia': { title: `How to Invoice as a Driving Instructor in Australia`, category: 'Invoicing', readTime: '12 min read' },
  'invoicing-lawyers-solicitors-legal-consultants-australia': { title: `How to Invoice as a Freelance Lawyer, Solicitor, or Legal Consultant in Australia`, category: 'Invoicing', readTime: '15 min read' },
  'invoicing-nutritionists-dietitians-australia': { title: `How to Invoice as a Freelance Nutritionist or Dietitian in Australia`, category: 'Invoicing', readTime: '13 min read' },
  'invoicing-mobile-app-developers-australia': { title: `How to Invoice as a Freelance Mobile App Developer in Australia`, category: 'Invoicing', readTime: '14 min read' },
};
