import { MetadataRoute } from 'next';
import { tools, CATEGORY_SLUGS } from './tools/tools-data';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://invoiceflow-teal.vercel.app';

  const competitors = ['quickbooks', 'xero', 'myob', 'zoho', 'freshbooks', 'wave', 'bonsai', 'honeybook'];
  const blogSlugs = ['how-to-create-tax-invoice-australia', 'gst-guide-australian-freelancers', 'freelance-rates-australia', 'invoicing-international-clients-australia', 'best-invoicing-software-australia', 'sole-trader-vs-company-australia', 'why-freelancers-dont-need-accounting-software', 'get-clients-pay-invoices-faster', 'freelance-invoice-checklist', 'tax-deductions-australian-freelancers', 'bas-guide-australian-freelancers', 'how-to-register-abn-australia', 'superannuation-for-freelancers-australia', 'late-payment-fees-australia-freelancers', 'how-to-start-freelancing-australia', 'freelance-contract-australia', 'record-keeping-freelancers-australia', 'how-to-quote-clients-freelancer', 'how-much-tax-freelancers-pay-australia', 'freelancer-insurance-guide-australia', 'how-to-accept-payments-freelancer-australia', 'sole-trader-tax-return-australia', 'contractor-vs-employee-australia', 'cashflow-management-freelancers-australia', 'working-from-home-tax-deductions-australia', 'freelancing-vs-full-time-employment-australia', 'how-to-price-freelance-services-australia', 'best-business-bank-accounts-freelancers-australia', 'how-to-find-freelance-clients-australia', 'freelance-portfolio-guide-australia', 'common-invoicing-mistakes-freelancers', 'how-to-chase-overdue-invoices-australia', 'freelancer-tax-calendar-australia-2026', 'payment-reminder-email-templates-freelancers', 'payg-instalments-australian-freelancers', 'how-to-handle-scope-creep-freelancer', 'how-to-raise-freelance-rates-australia', 'retainer-agreements-australian-freelancers', 'time-tracking-australian-freelancers', 'how-to-write-freelance-proposal-australia', 'freelance-client-red-flags-australia', 'how-to-fire-client-professionally-freelancer', 'freelance-bookkeeping-australia', 'invoice-payment-terms-explained', 'how-to-handle-client-disputes-freelancer-australia', 'freelance-tools-stack-australia', 'how-to-get-repeat-clients-freelancer', 'digital-marketing-freelancers-australia', 'ai-tools-for-freelancers-australia', 'transition-full-time-to-freelancing-australia', 'freelance-tax-mistakes-australia', 'deposit-invoicing-milestone-payments-freelancer', 'freelance-networking-australia', 'financial-planning-australian-freelancers', 'invoice-numbering-system-freelancers', 'invoice-email-templates-freelancers', 'intellectual-property-rights-freelancers-australia', 'managing-multiple-freelance-clients-australia', 'recurring-invoices-guide-freelancers', 'setting-boundaries-freelance-clients', 'freelance-business-plan-australia', 'client-onboarding-checklist-freelancers', 'freelance-work-life-balance-burnout-australia', 'how-to-send-first-invoice-freelancer', 'subcontracting-guide-australian-freelancers', 'credit-notes-refunds-australian-freelancers', 'eofy-tax-prep-checklist-freelancers-australia', 'freelance-project-management-deliver-on-time', 'vehicle-travel-expenses-freelancers-australia', 'personal-branding-freelancers-australia', 'how-to-scale-freelance-business-australia', 'freelance-negotiation-skills-australia', 'digital-products-freelancer-australia', 'freelance-cybersecurity-australia', 'email-marketing-freelancers-australia', 'invoice-vs-receipt-vs-quote-difference', 'proforma-invoice-guide-australian-freelancers', 'how-to-niche-down-freelancer-australia', 'government-grants-funding-australian-freelancers', 'non-paying-clients-legal-options-australia', 'freelancing-on-visa-australia-work-rights-tax', 'ato-audit-guide-australian-freelancers', 'professional-development-tax-deductions-freelancers-australia', 'diversify-freelance-income-streams-australia', 'freelancing-while-employed-australia', 'gst-registration-threshold-australian-freelancers', 'invoicing-expenses-reimbursements-freelancer-australia', 'invoicing-graphic-designers-australia', 'invoicing-web-developers-australia', 'invoicing-photographers-australia', 'invoicing-copywriters-content-writers-australia', 'invoicing-social-media-managers-australia', 'invoicing-videographers-video-editors-australia', 'invoicing-consultants-australia', 'invoicing-bookkeepers-bas-agents-australia', 'invoicing-personal-trainers-fitness-australia', 'invoicing-virtual-assistants-australia', 'invoicing-interior-designers-australia', 'invoicing-electricians-tradespeople-australia', 'invoicing-massage-therapists-allied-health-australia', 'invoicing-tutors-private-teachers-australia', 'invoicing-makeup-artists-hair-stylists-australia', 'invoicing-cleaners-cleaning-business-australia', 'invoicing-yoga-pilates-instructors-australia', 'invoicing-carpenters-builders-australia', 'invoicing-musicians-djs-australia', 'invoicing-architects-draftspeople-australia', 'invoicing-event-planners-wedding-coordinators-australia', 'invoicing-it-consultants-cybersecurity-australia', 'invoicing-landscapers-gardeners-australia', 'invoicing-caterers-private-chefs-australia', 'invoicing-plumbers-gas-fitters-australia', 'invoicing-life-coaches-business-coaches-australia', 'invoicing-dog-walkers-pet-sitters-australia', 'invoicing-accountants-tax-agents-bas-agents-australia', 'invoicing-translators-interpreters-australia', 'invoicing-ux-ui-designers-australia', 'invoicing-psychologists-counsellors-therapists-australia', 'invoicing-florists-floral-designers-australia', 'invoicing-driving-instructors-australia', 'invoicing-lawyers-solicitors-legal-consultants-australia', 'invoicing-nutritionists-dietitians-australia', 'invoicing-mobile-app-developers-australia'];

  return [
    { url: baseUrl, lastModified: new Date(), changeFrequency: 'weekly', priority: 1.0 },
    { url: `${baseUrl}/about`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/features`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/invoice-generator`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/gst-compliance`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/payment-tracking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/ai-powered`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/expense-tracking`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/client-management`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/recurring-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/features/multi-currency`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/pricing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    // Persona landing pages
    { url: `${baseUrl}/for/sole-traders`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/freelancers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/contractors`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/tradies`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/consultants`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/creatives`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/coaches`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/photographers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/virtual-assistants`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/personal-trainers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/web-developers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/writers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/marketing-professionals`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/accountants`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/beauty-hair`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/cleaners`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/event-planners`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/real-estate-agents`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/tutors`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/graphic-designers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/allied-health`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/lawyers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/architects`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/musicians`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/for/it-consultants`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    // City/location landing pages
    { url: `${baseUrl}/in/melbourne`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/sydney`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/brisbane`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/perth`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/adelaide`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/gold-coast`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/canberra`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/hobart`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/in/darwin`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/templates`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    // Integration landing pages (payment/accounting SEO)
    { url: `${baseUrl}/integrations`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/stripe`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/paypal`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/xero`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/bank-feeds`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/google-sheets`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/myob`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/quickbooks`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/integrations/zapier`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    // Use case landing pages (billing workflow SEO)
    { url: `${baseUrl}/use-cases`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/recurring-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/milestone-billing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/time-billing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/quote-to-invoice`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/deposit-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/international-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/expense-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/batch-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/retainer-billing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/overdue-management`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/credit-notes`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/use-cases/proforma-invoicing`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    // Guides (comprehensive how-to content)
    { url: `${baseUrl}/guides`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/gst-for-freelancers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/invoicing-101`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/getting-paid-faster`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/setting-freelance-rates`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/tax-guide-freelancers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/abn-guide`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/superannuation-for-freelancers`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/guides/eofy-guide`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    // Glossary (business term definitions for informational SEO)
    { url: `${baseUrl}/glossary`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/abn`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/gst`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/bas`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/payg`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-invoice`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/sole-trader`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/credit-note`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/superannuation`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/invoice`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tfn`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/professional-indemnity`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/acn`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/accounts-receivable`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/cash-flow`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/pty-ltd`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/depreciation`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/payment-terms`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/contractor-vs-employee`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/income-tax`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/purchase-order`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/profit-and-loss`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/retainer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/quote`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/scope-creep`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/public-liability`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/invoice-factoring`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/bookkeeping`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/input-tax-credits`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/billable-hours`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/profit-margin`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/workers-compensation`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/business-structure`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/capital-gains-tax`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/statement-of-account`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/hourly-rate`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/bad-debt`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/accounts-payable`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/dividend`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/late-payment-interest`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-return`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/withholding-tax`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-deduction`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/gig-economy`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/fringe-benefits-tax`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/invoice-template`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/overdue-invoice`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/business-expenses`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/cash-basis-accounting`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/record-keeping`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-agent`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/break-even-point`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/working-capital`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/registered-business-name`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/net-income`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-offset`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/invoice-aging`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/financial-year`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-planning`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/billing-cycle`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/expense-report`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/medicare-levy`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/business-insurance`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/tax-residency`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/subcontractor`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/accrual-accounting`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/bank-reconciliation`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/invoice-number`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/debt-recovery`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/personal-services-income`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/balance-sheet`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/recurring-invoice`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/partnership`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/revenue`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/cash-flow-forecast`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/remittance-advice`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/milestone-payment`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/trust`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/instant-asset-write-off`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/work-from-home-deductions`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/chart-of-accounts`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/pro-rata`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/deposit`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/overhead`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/double-entry-bookkeeping`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/pricing-strategy`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/cash-flow-statement`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/general-ledger`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/glossary/equity`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/tools`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    // All 100 free tools — dynamically generated from tools-data.ts
    ...tools.map((tool) => ({
      url: `${baseUrl}${tool.href}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    })),
    // Tool category pages
    ...CATEGORY_SLUGS.map((cat) => ({
      url: `${baseUrl}/tools/category/${cat}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    // Alternative-to landing pages (high buyer-intent SEO)
    { url: `${baseUrl}/alternative-to`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    ...competitors.map((slug) => ({
      url: `${baseUrl}/alternative-to/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    })),
    { url: `${baseUrl}/compare`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    ...competitors.map((slug) => ({
      url: `${baseUrl}/compare/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
    // Head-to-head competitor comparison pages (high buyer-intent)
    { url: `${baseUrl}/compare/xero-vs-myob`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/xero-vs-freshbooks`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/freshbooks-vs-wave`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/myob-vs-quickbooks`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/xero-vs-quickbooks`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/quickbooks-vs-freshbooks`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/quickbooks-vs-wave`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/myob-vs-freshbooks`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/xero-vs-wave`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/freshbooks-vs-zoho`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/myob-vs-wave`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/wave-vs-zoho`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/xero-vs-zoho`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/quickbooks-vs-zoho`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare/myob-vs-zoho`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/blog/profession-guides`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    ...['invoicing', 'tax', 'business', 'getting-started', 'getting-paid', 'growth', 'pricing', 'profession-guides'].map((cat) => ({
      url: `${baseUrl}/blog/category/${cat}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...blogSlugs.map((slug) => ({
      url: `${baseUrl}/blog/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    { url: `${baseUrl}/login`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/signup`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/privacy`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/terms`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
  ];
}
